# Generated by Django 4.2.7 on 2023-11-16 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='formulario',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.genero'),
        ),
    ]
