# Generated by Django 4.2.7 on 2023-11-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0003_genero_alter_formulario_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='genero',
            new_name='nombre_genero',
        ),
    ]
