# Generated by Django 4.2.7 on 2023-11-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0004_rename_genero_genero_nombre_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
