# Generated by Django 4.2.7 on 2023-11-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0005_delete_formulario_delete_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=20)),
                ('primer_nombre', models.TextField(max_length=50)),
                ('segundo_nombre', models.TextField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.TextField(max_length=50)),
                ('apellido_materno', models.TextField(max_length=50)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.TextField(max_length=50)),
                ('curso', models.TextField(max_length=10)),
                ('sala', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=20)),
                ('primer_nombre', models.TextField(max_length=50)),
                ('segundo_nombre', models.TextField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.TextField(max_length=50)),
                ('apellido_materno', models.TextField(max_length=50)),
                ('edad', models.IntegerField()),
                ('parentesco', models.TextField(max_length=50)),
                ('nacionalidad', models.TextField(max_length=50)),
            ],
        ),
    ]
