# Generated by Django 4.2.7 on 2023-11-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0006_alumno_apoderado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
                ('correo', models.TextField(max_length=100)),
                ('cargo', models.TextField(max_length=30)),
                ('asignatura', models.TextField(max_length=50)),
            ],
        ),
    ]
